apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: dcm-development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dcm-api
      environment: development
  template:
    metadata:
      labels:
        app: dcm-api
        environment: development
    spec:
      serviceAccountName: dcm-api-sa
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: api
          image: ghcr.io/ditwordhet/api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: '100m'
              memory: '128Mi'
            limits:
              cpu: '500m'
              memory: '512Mi'
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          envFrom:
            - secretRef:
                name: dcm-secrets
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
  namespace: dcm-development
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dcm-api-sa
  namespace: dcm-development
