apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-deployment
  namespace: dcm-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dcm-bot
      environment: development
  template:
    metadata:
      labels:
        app: dcm-bot
        environment: development
    spec:
      serviceAccountName: dcm-bot-sa
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: bot
          image: ghcr.io/ditwordhet/bot:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '100m'
              memory: '128Mi'
            limits:
              cpu: '300m'
              memory: '256Mi'
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /ready
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          ports:
            - containerPort: 3001
          envFrom:
            - secretRef:
                name: dcm-secrets
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bot-hpa
  namespace: dcm-development
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bot-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dcm-bot-sa
  namespace: dcm-development
