apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: dcm-development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dcm-web
      environment: development
  template:
    metadata:
      labels:
        app: dcm-web
        environment: development
    spec:
      serviceAccountName: dcm-web-sa
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
      - name: web
        image: ghcr.io/ditwordhet/web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        env:
        - name: API_URL
          value: "http://api-service"
        envFrom:
        - secretRef:
            name: dcm-secrets
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-hpa
  namespace: dcm-development
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dcm-web-sa
  namespace: dcm-development