apiVersion: v1
kind: Secret
metadata:
  name: dcm-secrets
  namespace: dcm-staging
type: Opaque
stringData:
  # Database
  DB_HOST: 'VERVANG_MET_DB_HOST'
  DB_PORT: '5432'
  DB_NAME: 'dcm_staging'
  DB_USER: 'VERVANG_MET_DB_USER'
  DB_PASSWORD: 'VERVANG_MET_DB_PASSWORD'

  # API Keys
  API_KEY: 'VERVANG_MET_API_KEY'

  # JWT
  JWT_SECRET: 'VERVANG_MET_JWT_SECRET'

  # Redis
  REDIS_HOST: 'VERVANG_MET_REDIS_HOST'
  REDIS_PORT: '6379'
  REDIS_PASSWORD: 'VERVANG_MET_REDIS_PASSWORD'
