apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: dcm-staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dcm-api
      environment: staging
  template:
    metadata:
      labels:
        app: dcm-api
        environment: staging
    spec:
      serviceAccountName: dcm-api-sa
      containers:
        - name: api
          image: dcm-api:stable
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: '200m'
              memory: '256Mi'
            limits:
              cpu: '1000m'
              memory: '1Gi'
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          envFrom:
            - secretRef:
                name: dcm-secrets
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
  namespace: dcm-staging
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-deployment
  minReplicas: 3
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dcm-api-sa
  namespace: dcm-staging
