apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-deployment
  namespace: dcm-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dcm-bot
      environment: staging
  template:
    metadata:
      labels:
        app: dcm-bot
        environment: staging
    spec:
      serviceAccountName: dcm-bot-sa
      containers:
      - name: bot
        image: dcm-bot:stable
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /ready
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
        - containerPort: 3001
        envFrom:
        - secretRef:
            name: dcm-secrets
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bot-hpa
  namespace: dcm-staging
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bot-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dcm-bot-sa
  namespace: dcm-staging