apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: dcm-development
  labels:
    app: dcm-api
    environment: development
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: dcm-api
    environment: development