name: CI Pipeline

on:
  push:
    branches:
      - develop
      - 'feature/**'
      - 'test/**'
  pull_request:
    branches:
      - develop

env:
  REGISTRY: ghcr.io
  REPO_NAME: ditwordhet

jobs:
  set-env:
    name: Set Environment Variables
    runs-on: ubuntu-latest
    outputs:
      repo_owner: ${{ steps.lowercase.outputs.repo_owner }}
    steps:
      - id: lowercase
        run: |
          echo "repo_owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

  validate:
    needs: set-env
    name: Validate Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          scope: '@ditwordhet'

      - name: Clean install dependencies
        run: |
          rm -rf node_modules
          npm ci

      - name: Run linting
        run: |
          npm run lint

      - name: Check formatting
        run: |
          npm run format:check

      - name: TypeScript check
        run: |
          npm run type-check

  test:
    name: Run Tests
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          scope: '@ditwordhet'

      - name: Clean install dependencies
        run: |
          rm -rf node_modules
          npm ci

      - name: Run tests
        run: |
          npm run test:ci

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/

  build:
    name: Build Containers
    needs: [test, set-env]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [api, web, bot]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.package }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.package }}-

      - name: Build and load image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packages/${{ matrix.package }}/Dockerfile
          push: false
          load: true
          tags: ${{ env.REGISTRY }}/${{ needs.set-env.outputs.repo_owner }}/${{ env.REPO_NAME }}-${{ matrix.package }}:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: List images
        run: docker images

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  scan:
    name: Security Scan
    needs: [build, set-env]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [api, web, bot]
    steps:
      - name: Wait for images to be available
        run: |
          # Wacht tot de images beschikbaar zijn
          for i in {1..30}; do
            if docker images | grep ${{ env.REGISTRY }}/${{ needs.set-env.outputs.repo_owner }}/${{ env.REPO_NAME }}-${{ matrix.package }}; then
              echo "Image found"
              exit 0
            fi
            echo "Waiting for image... ($i/30)"
            sleep 2
          done
          echo "Image not found after timeout"
          exit 1

      - name: Verify image
        run: docker images

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ needs.set-env.outputs.repo_owner }}/${{ env.REPO_NAME }}-${{ matrix.package }}:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: success()
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'trivy'

      - name: Run Snyk
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

  publish:
    name: Publish Images
    needs: [scan, set-env]
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      security-events: write
    strategy:
      matrix:
        package: [api, web, bot]
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packages/${{ matrix.package }}/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ needs.set-env.outputs.repo_owner }}/${{ env.REPO_NAME }}-${{ matrix.package }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ needs.set-env.outputs.repo_owner }}/${{ env.REPO_NAME }}-${{ matrix.package }}:latest
